
CREATE TABLE IF NOT EXISTS  PERSONA
    (
        ID INTEGER PRIMARY KEY,
        NOMBRE TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS  ROL
    (
        ID INTEGER PRIMARY KEY,
        ROL TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS  GENERO
    (
        ID INTEGER PRIMARY KEY,
        GENERO TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS PELICULA
   (
    ID INTEGER PRIMARY KEY,
    TITULO TEXT NOT NULL,
    ESTRENO REAL,
    DURACION INTEGER,
    PRESUPUESTO INTEGER,
    RECAUDACION INTEGER,
    POSTER TEXT,
    TMBD_ID TEXT
   );

CREATE TABLE IF NOT EXISTS PELICULA_GENERO
(
  PELICULA INTEGER,
  GENERO INTEGER,
  PRIMARY KEY (PELICULA, GENERO),
  FOREIGN KEY (PELICULA)
    REFERENCES PELICULA(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  FOREIGN KEY (GENERO)
    REFERENCES GENERO (ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS CREDITOS
(
  PERSONA INTEGER,
  PELICULA INTEGER,
  ROL INTEGER,
  DETALLE TEXT,
  PRIMARY KEY (PERSONA, PELICULA, ROL),
  FOREIGN KEY (PERSONA)
    REFERENCES PERSONA(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  FOREIGN KEY (PELICULA)
    REFERENCES PELICULA(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  FOREIGN KEY (ROL)
    REFERENCES ROL (ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

INSERT INTO ROL (ID, ROL) VALUES (1, "Director");
INSERT INTO ROL (ID, ROL) VALUES (2, "Directora");
INSERT INTO ROL (ID, ROL) VALUES (3, "Actor");
INSERT INTO ROL (ID, ROL) VALUES (4, "Actriz");
INSERT INTO ROL (ID, ROL) VALUES (5, "Guionista");


INSERT INTO GENERO (ID, GENERO) VALUES (35, "Comedia");
INSERT INTO GENERO (ID, GENERO) VALUES (53, "Thriller");
INSERT INTO GENERO (ID, GENERO) VALUES (18, "Drama");
INSERT INTO GENERO (ID, GENERO) VALUES (37, "Western");

INSERT INTO PERSONA (ID, NOMBRE) VALUES (20738, "Song Kang-ho");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (115290, "Lee Sun-kyun");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (556435, "Cho Yeo-jeong");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (1255881, "Choi Woo-shik");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (1442583, "Park So-dam");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (21684, "Bong Joon Ho");

INSERT INTO PERSONA (ID, NOMBRE) VALUES (190, "Clint Eastwood");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (3265, "Eli Wallach");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (4078, "Lee Van Cleef");
INSERT INTO PERSONA (ID, NOMBRE) VALUES (4385, "Sergio Leone");



INSERT INTO Pelicula (ID, TITULO, ESTRENO, DURACION, PRESUPUESTO, RECAUDACION, POSTER)
VALUES (496243, 'Parasite', '2019-12-25', 133, 11363000, 257591776, '7IiTTgloJzvGI1TAYymCfbfl3vT.jpg');
INSERT INTO Pelicula (ID, TITULO, ESTRENO, DURACION, PRESUPUESTO, RECAUDACION, POSTER)
VALUES (429, 'The Good, the Bad and the Ugly', '1969-04-17', 133, 1200000, 38900000, 'bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg');

INSERT INTO PELICULA_GENERO (PELICULA, GENERO) VALUES (496243, 35);
INSERT INTO PELICULA_GENERO (PELICULA, GENERO) VALUES (496243, 53);
INSERT INTO PELICULA_GENERO (PELICULA, GENERO) VALUES (496243, 18);
INSERT INTO PELICULA_GENERO (PELICULA, GENERO) VALUES (429, 37);

INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (20738, 496243, 3, 'Kim Ki-taek');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (115290, 496243, 3, 'Park Dong-ik');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (556435, 496243, 4, 'Yeon-kyo');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (1255881, 496243, 3, 'Ki-jung');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (21684, 496243, 1, NULL);

INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (190, 429, 3, 'Blondie');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (3265, 429, 3, 'Tuco Ramirez');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (4078, 429, 3, 'Sentenza - Angel Eyes');
INSERT INTO CREDITOS (PERSONA, PELICULA, ROL, DETALLE) VALUES (4385, 429, 1, NULL);
